services:
    db:
        image: mysql:8.0
        env_file: .env
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
        volumes:
            - db-data:/var/lib/mysql
    web:
        build:
            context: .
            args:
                PROJECT_NAME: ${PROJECT_NAME}
        env_file: .env
        environment:
            RAILS_ENV: development
            PROJECT_NAME: ${PROJECT_NAME}
            RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
            DATABASE_HOST: db
            DATABASE_USERNAME: ${DATABASE_USERNAME}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        depends_on:
            - db
        ports:
            - "${APP_PORT:-3000}:3000"
        volumes:
            - .:/${PROJECT_NAME}
            - bundle:/usr/local/bundle
        working_dir: /${PROJECT_NAME}
volumes:
    db-data:
    bundle:
